### PR TITLE
Text fixes

### PR DESCRIPTION
**Pull request by kmanaseryan**
Related issue:
https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/509

## Demo
Helptext in Unique ID field 👇
image

Missing "d" typo in System Records tooltip 👇
image

Alphabetized media type options in dropdown 👇
image

Data publishing frequency options is ordered from most to least frequent 👇
image

### CODE REVIEW

**Comment by anuveyatsu** [comment]
@kmanaseryan sorting 'Data Publishing Frequency' must be challenging 😄 I'm not sure where should we put 'irregular' one but it looks correct to me to have it in the end of the list.

**Review by anuveyatsu — APPROVED** [review]
👍

**Comment by kmanaseryan** [comment]
> @kmanaseryan sorting 'Data Publishing Frequency' must be challenging 😄 I'm not sure where should we put 'irregular' one but it looks correct to me to have it in the end of the list.

Did a lot of research to come with that order 😅

**Comment by osahon-okungbowa** [comment]
@kmanaseryan @anuveyatsu i agree!! sorting the update frequency must have been challenging 😆 !!
thanks for doing the needed research @kmanaseryan 👏
this looks very good to me. You can go ahead and merge 👍

**Pull request merged**
