### PR TITLE
Remove Duplicate 'Add Dataset' Button

### PR DESCRIPTION
**Pull request by nickumia-reisys**
Related to https://github.com/GSA/data.gov/issues/3613

Fixes the webassets migration from PY2 to PY3.  References:
- https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#web-assets-js-and-css
- https://docs.ckan.org/en/2.9/theming/webassets.html

### CODE REVIEW

**Review by btylerburton — APPROVED** [review]

**Comment by btylerburton** [comment]
Looks good, but I have zero context so take that approval with a grain of salt. :)

**Review by jbrown-xentity — APPROVED** [review]

**Comment by jbrown-xentity** [comment]
❤️ tests!!!!

**Comment by nickumia-reisys** [comment]
@jbrown-xentity Can we just not require CKAN 2.8 tests?  It's literally passing locally and we know cypress isn't reliable 😢

**Comment by nickumia-reisys** [comment]
Inventory is entirely off of FCS too and that's the only reason we needed FCS.

**Pull request merged**
