### PR TITLE
Fix/parent dataset

### PR DESCRIPTION
**Pull request by anuveyatsu**
Demo:

https://www.awesomescreenshot.com/video/1142273?key=a81a5bd2252938dd7e8974b2a0a8daf6

### CODE REVIEW

**Comment by kmanaseryan** [comment]
@anuveyatsu I've tested locally, but haven't been able to see the autocomplete. You can see in the screenshot below, it gets list but doesn't show the dropdown.
https://www.loom.com/share/e2d7f0329d894386b08c1a7057fc5295

**Comment by kmanaseryan** [comment]
Also, tried to delete the dataset added from original CKAN, but couldn't.
https://www.loom.com/share/9aa275cf71d04ad1a1752ebdecd91846

**Comment by anuveyatsu** [comment]
@kmanaseryan not sure why you couldn't see the autocomplete options, can you try with the latest build? It's loading just fine for me.

**Comment by anuveyatsu** [comment]
@kmanaseryan on the second point can you inspect body of the package_update call to verify what is wrong with `parent_dataset` field?

**Review by osahon-okungbowa — APPROVED** [review]
all good

**Pull request merged**
