### PR TITLE
Fix encoding bug in create resource

### PR DESCRIPTION
**Pull request by kmanaseryan**
- Able to create resource where the name field has a special char (e.g. &)

### CODE REVIEW

**Comment by adborden** [comment]
Can you add a test for this?

**Review by anuveyatsu — APPROVED** [review]
LGTM

**Review by anuveyatsu — CHANGES_REQUESTED** [review]
Let's add test first to make sure all scenarios are considered.

I suggest using something like https://www.npmjs.com/package/cypress-file-upload for testing following cases:

1. File upload without any special characters in metadata (name etc.)
2. File upload with special characters in metadata
3. Link to data without any special characters in metadata
4. Link to data with special characters in metadata

**Review by anuveyatsu — APPROVED** [review]
I've now added tests.

**Pull request merged**
