### PR TITLE
Fix/url edit

### PR DESCRIPTION
**Pull request by kmanaseryan**
Related issue: https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/471

image

### CODE REVIEW

**Review by osahon-okungbowa — APPROVED** [review]
all good

**Review by starsinmypockets — CHANGES_REQUESTED** [review]
There's an off-by-one error when translating title to url:

**Comment by kmanaseryan** [comment]
https://www.loom.com/share/d87fecb85638428dbe0af99ca8058375

**Review by starsinmypockets — APPROVED** [review]
LGTM

**Pull request merged**
